<?php
/* @var $this Powerbody_Ingredients_Block_View */
/* @var $currentProductModel Mage_Catalog_Model_Product */
$currentProductModel = $this->getCurrentProduct();
$productType = $currentProductModel->getData('type_id');
?>

<?php if ($productType === Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE): ?>
    <?php $simpleProductArray = $this->getSimpleProductCollectionForConfigurable(); ?>
    <?php if(false === empty($simpleProductArray)): ?>
        <select name="ingredient-configurable-product-id" id="ingredient-configurable-product-id">
            <?php foreach($simpleProductArray as $simpleProductModel): ?>
                <?php /* @var $simpleProductModel Mage_Catalog_Model_Product */ ?>
                <option value="<?php echo $simpleProductModel->getId(); ?>"><?php echo $simpleProductModel->getName(); ?></option>
            <?php endforeach; ?>
        </select>
    <?php endif; ?>
<?php else: ?>
    <input type="hidden" name="ingredient-simple-product-id"
        id="ingredient-simple-product-id" value="<?php echo $currentProductModel->getId(); ?>"/>
<?php endif; ?>

<div class="product-ingredient"></div>

<script>
    jQuery(document).ready(function($) {

        function getLabel() {
            var productId = null;

            if ($('#ingredient-configurable-product-id').length > 0) {
                productId = $('#ingredient-configurable-product-id').val();
            }

            if ($('#ingredient-simple-product-id').length > 0) {
                productId = $('#ingredient-simple-product-id').val();
            }

            if (productId != null) {
                $.ajax({
                    method: "get",
                    dataType: "json",
                    url: "<?php echo $this->getIngredientUrl(); ?>",
                    data: { productId: productId }
                })
                .done(function (result) {
                    if (true === result.success) {
                        $('.product-ingredient').empty();
                        $('.product-ingredient').html(
                            '<img src="' + result.data + '"/>'
                        );
                    }
                });
            }
        }

        getLabel();

        $(document).on('change', '#ingredient-configurable-product-id', function(){
            getLabel();
        });
    });
</script>
